### ISSUE TITLE
docs: code miss in react three fiber tutorial 

### ISSUE THREAD

**Issue by naotaro0123** [pmndrs/website#125]
Hi, Thank you for the react three fiber tutorial.
I found one mistake on loading textures page.
https://docs.pmnd.rs/react-three-fiber/getting-started/loading-textures

incorrect: `<sphereGeometry args={[1, 100, 100]} map={colorMap} />`
correct: `<meshStandardMaterial  map={colorMap} />`

**Comment by CodyJasonBennett** [comment]
Thanks for investigating. Fixed with #135.
