### ISSUE TITLE
[docs/zustand] zustand bear image is missing on the zustand docs introduction page

### ISSUE THREAD

**Issue by manan30** [pmndrs/website#131]
It looks like the zustand bear image is missing on https://docs.pmnd.rs/zustand/introduction

<img width="1792" alt="Screen Shot 2021-07-17 at 9 37 52 PM" src="https://user-images.githubusercontent.com/12088143/126053944-5df12e8e-d615-4fc0-b446-4effda8f560d.png">

**Comment by CodyJasonBennett** [comment]
Looks liked you fixed this. Thanks!
