### ISSUE TITLE
Links broken in "How it works > Render loop"

### ISSUE THREAD

**Issue by saoirse-zee** [pmndrs/website#134]
The links in this section are broken: https://github.com/pmndrs/website/blob/docs/docs/react-three-fiber/advanced/how-it-works.mdx#render-loop

For instance, this link leads to a 404: https://github.com/pmndrs/website/blob/docs/docs/react-three-fiber/advanced/docs/recipes/effects

**Comment by SaraVieira** [comment]
Both of those are returning 404, where did you find these links?

**Comment by CodyJasonBennett** [comment]
Current section would be in [`docs/react-three-fiber/tutorials/how-it-works.mdx`](https://github.com/pmndrs/website/blob/docs/docs/react-three-fiber/tutorials/how-it-works.mdx#render-loop).

**Comment by CodyJasonBennett** [comment]
Seems that those sections were never added (commit traced to 6147e7b). I'll go check the R3F repo to see what's missing.

**Comment by SaraVieira** [comment]
Thank yoU!

**Comment by CodyJasonBennett** [comment]
I did a massive patch in #163, with these included.

However, I have started piecing together some of the missing material in #165.

**Comment by CodyJasonBennett** [comment]
This was resolved in #163 but we'll be patching up missing recipes with v8.
