### ISSUE TITLE
feature: DarkMode

### ISSUE THREAD

**Issue by njm222** [pmndrs/website#137]
It would be great if there was a 'DarkMode' for the docs

https://tailwindcss.com/docs/dark-mode

**Comment by CodyJasonBennett** [comment]
Thoughts on making this toggleable behind a button rather than device preferences?

**Comment by njm222** [comment]
Yes definitely toggleable! market already has this implemented if you don't want to play around with colours too much, just grab the same styles

**Comment by saitonakamura** [comment]
I've vote for tri state button (I'm a heavy user of device preferences that changes by time of the day): device preferences/light/dark, device preference by default
