### ISSUE TITLE
[docs/jotai] link to sandbox for atomWithImmer broken

### ISSUE THREAD

**Issue by nicekiwi** [pmndrs/website#181]
Example Sandbox for `atomWithImmer` is broken or missing.

https://docs.pmnd.rs/jotai/integrations/immer

`<Codesandbox id="8zrqs" />`

**Comment by dai-shi** [comment]
That codesandbox is deleted?? @Aslemammad Is it yours?

**Comment by CodyJasonBennett** [comment]
Original link is: https://codesandbox.io/s/jotai-immer-example-8zrqs. This came from commit 189803a982d2df86ccd444787a278e82cc5fbf13.

**Comment by dai-shi** [comment]
It is originally from https://github.com/pmndrs/jotai/commit/a1e0c4ea1f948865cbbdb184da259415afc2e0a2.

**Comment by Aslemammad** [comment]
Yep, I don't remember it exactly. But I feel it is my own!
And actually I've never touched them since creating jotai examples!
Really sorry for that!
@dai-shi What example do I need to create now? same second example but with atomWithImmer?

**Comment by dai-shi** [comment]
I don't remember either. Feel free to create a new one. It can be the same, or something new (as you now have much deeper understanding than back then.)

**Comment by Aslemammad** [comment]
Here's the [codesandbox](https://codesandbox.io/s/atomwithimmer-example-vtp3j)!

**Comment by CodyJasonBennett** [comment]
Awesome. Do you mind updating [docs/jotai/integrations/immer.mdx](https://github.com/pmndrs/website/blame/docs/docs/jotai/integrations/immer.mdx#L45)?

**Comment by Aslemammad** [comment]
Yep, going to do this!

**Comment by CodyJasonBennett** [comment]
Cool. Closing as resolved with #183.
