### ISSUE TITLE
Camera shake example

### ISSUE THREAD

**Issue by djave-co** [pmndrs/website#224]
On https://docs.pmnd.rs/drei/cameras/camera-shake

I think the ID of the camera shake storybook should be:

    staging-camerashake--camera-shake-story

Or the iframe URL should be:

    iframe.html?id=staging-camerashake--camera-shake-story&args=pitchFrequency:0.3;rollFrequency:0.1;yawFrequency:0.4

**Comment by gsimone** [comment]
Can you make a PR with the fix? The branch is `docs`

**Comment by djave-co** [comment]
Yep no worries, would you mind double checking I have done it right? I couldn't find any info on the `StoryBook` component.

https://github.com/pmndrs/website/pull/226

**Comment by CodyJasonBennett** [comment]
Fix is live at https://docs.pmnd.rs/drei/cameras/camera-shake.
