### ISSUE TITLE
docs: / Drei Storybook example errors

### ISSUE THREAD

**Issue by Gsirron** [pmndrs/website#234]
Hi ,

 Just going through the Drei docs and have noticed the following examples all have storybook errors.

https://docs.pmnd.rs/drei/shaders/stars
https://docs.pmnd.rs/drei/misc/center
https://docs.pmnd.rs/drei/misc/reflector
https://docs.pmnd.rs/drei/modifiers/edge-split
https://docs.pmnd.rs/drei/modifiers/use-simplification
https://docs.pmnd.rs/drei/modifiers/use-tessellation
https://docs.pmnd.rs/drei/shapes/parametric
https://docs.pmnd.rs/drei/abstractions/enviroment
https://docs.pmnd.rs/drei/shaders/contact-shadows
https://docs.pmnd.rs/drei/shaders/sky

**Comment by CodyJasonBennett** [comment]
Thanks, gone through these and they were grouped into staging.
