### ISSUE TITLE
no favicon in the site

### ISSUE THREAD

**Issue by Deep-Codes** [pmndrs/website#27]
Refer this : [Favicon Checker](https://realfavicongenerator.net/favicon_checker?protocol=https&site=docs.pmnd.rs%2Freact-three-fiber%2Fgetting-started%2Finstallation)

<img width="576" alt="Screenshot 2021-04-19 at 3 26 10 AM" src="https://user-images.githubusercontent.com/61158210/115162079-ff286580-a0be-11eb-9bd5-641c2c23a04b.png">

**Comment by CodyJasonBennett** [comment]
Thanks! This was fixed in 3e6da6a68112338a9643e1d05263d192fea6ac28.
