### ISSUE TITLE
Bug : Mobile View - Side Menu Background Transparency Issue

### ISSUE THREAD

**Issue by Harish-M-2003** [pmndrs/website#271]
## Summary

When accessing the Zustand documentation on mobile devices, an issue arises where the side menu background turns transparent upon opening. This behavior significantly hinders the readability of the content, making navigation and comprehension challenging for users on smaller screens. This problem is not observed on desktop screens, indicating a responsive design issue that needs attention for an optimal user experience.

I've opened a new discussion thread #2296 related to this issue. In the discussion, we can further explore the details and potential solutions. Feel free to join the conversation there. 

[Discussion](https://github.com/pmndrs/zustand/discussions/2296)

## 1.)
<img width="342" alt="Screenshot 2024-01-18 195834" src="https://github.com/pmndrs/zustand/assets/124487595/569d4b06-d3b0-4beb-809f-6d2c07ac8820">

## 2.)
<img width="947" alt="Screenshot 2024-01-18 200929" src="https://github.com/pmndrs/zustand/assets/124487595/c3aeadf2-8674-4851-89b7-ceed42546950">

**Comment by CodyJasonBennett** [comment]
This fell out in #270 when I touched up missing sections. Will see which component was affected.
