### ISSUE TITLE
using-with-react-spring typo

### ISSUE THREAD

**Issue by philcon93** [pmndrs/website#36]
[using-with-react-spring](https://github.com/pmndrs/website/blob/docs/docs/react-three-fiber/getting-started/using-with-react-spring.mdx) looks to have a typo in the code example:

 ```
const { active } = useSpring({ scale: active ? 1.5 : 1 })
```

I believe we want the const to be `scale` as the next example uses that on the mesh?

The docs are amazing btw!

**Comment by SaraVieira** [comment]
Thank you!!

Fixed here: https://github.com/pmndrs/website/commit/d082768e99308a424490c193904ff69ed05db01c
