### ISSUE TITLE
Docs: Search hint text is obscured in header for mobile

### ISSUE THREAD

**Issue by CodyJasonBennett** [pmndrs/website#50]
Aside from the typo in the logo text, we'll need to make this text more accessible and/or update the hint text to match the input scheme.

![image](https://user-images.githubusercontent.com/23324155/115960159-625a3380-a4d5-11eb-8d91-ced11c6db826.png)

**Comment by SaraVieira** [comment]
I think just removing the part on quotes would work no?

**Comment by jure** [comment]
One way would be to do something like:

```html
<div type="search" class="appearance-none w-full h-full p-4">
  <span>Quick search</span>
  <span class="invisible sm:visible">("/" to focus)</span>
</div>
```

I checked how Tailwind does it on their docs site, as that works neatly, and it is the same idea:
```html
<span>Quick search<span class="hidden sm:inline"> for anything</span></span>
```

<img width="1434" alt="Screenshot 2021-04-26 at 23 05 21" src="https://user-images.githubusercontent.com/238667/116150674-fbf73000-a6e3-11eb-86b4-229bae83c9bd.png">
<img width="498" alt="Screenshot 2021-04-26 at 23 05 53" src="https://user-images.githubusercontent.com/238667/116150682-fef22080-a6e3-11eb-88f7-e5d0fe7f9f66.png">


Following their approach we'd have something like this (copy & paste-able):
```html
<button type="button" class="group leading-6 font-medium flex items-center space-x-3 sm:space-x-4 hover:text-gray-600 transition-colors duration-200 w-full py-2">
	<svg width="24" height="24" fill="none" class="text-gray-400 group-hover:text-gray-500 transition-colors duration-200">
		<path d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
	</svg>
	<span>Quick search
		<span class="hidden sm:inline"> for anything</span>
	</span>
	<span style="opacity: 1;" class="hidden sm:block text-gray-400 text-sm leading-5 py-0.5 px-1.5 border border-gray-300 rounded-md">
		<span class="sr-only">Press </span>
		<kbd class="font-sans">
			<abbr title="Forward slash" class="no-underline">/</abbr>
		</kbd>
		<span class="sr-only"> to search</span>
	</span>
</button>
```

Small:
<img width="314" alt="Screenshot 2021-04-26 at 23 12 27" src="https://user-images.githubusercontent.com/238667/116151453-e6363a80-a6e4-11eb-863c-c2dc7b466c29.png">


Other sizes:
<img width="314" alt="Screenshot 2021-04-26 at 23 12 16" src="https://user-images.githubusercontent.com/238667/116151467-ea625800-a6e4-11eb-927e-c52929877965.png">


Would this work? Happy to tweak it and chuck it into a small PR.

**Comment by CodyJasonBennett** [comment]
Looks good. The icon makes this much clearer, which was my primary concern.

**Comment by SaraVieira** [comment]
Perfect! Updating it :)
