### ISSUE TITLE
Search is very slow

### ISSUE THREAD

**Issue by JohnAnon9771** [pmndrs/website#59]
Very slow search

When you type "Ty" in the entry, it takes up to 15 seconds to show the result, depending on the machine you are using. The documentation should be lighter... :(

I recommend removing the <code>const preview</code> when the result has no description in the **SearchItem** component because with each change in the input it is recalculating and pulling all the **MDX** to assemble the component and this is very expensive.

![image](https://user-images.githubusercontent.com/42195321/116493440-27f5eb00-a875-11eb-846f-e00034a0fbb3.png)

**Comment by gsimone** [comment]
Thanks John! Would you like to submit a PR?

**Comment by SaraVieira** [comment]
Closed by a PR by @CodyJasonBennett , should be live in 10m :)
