### ISSUE TITLE
update react spring

### ISSUE THREAD

**Issue by SaraVieira** [pmndrs/website#62]
The wesbite is using an old version of react spring that makes an unwanted error show up

**Comment by CodyJasonBennett** [comment]
Looks like [`components/Modal.tsx`](https://github.com/pmndrs/website/blob/docs/components/Modal.tsx) and [`components/LibSwitcher.tsx`](https://github.com/pmndrs/website/blob/docs/components/LibSwitcher.tsx) will have to be updated.

I can't find anything else other than react-spring docs, which we'll have to update with our next patch anyway.

**Comment by CodyJasonBennett** [comment]
The warning has been vanquished in #113.
