### ISSUE TITLE
docs: license is attributed to Shu Ding of Vercel

### ISSUE THREAD

**Issue by CodyJasonBennett** [pmndrs/website#63]
As the title suggests, the license was updated early on in 6147e7b9db56ee19e935d1e2c1355f4be73b1323. Is this intentional?

**Comment by drcmda** [comment]
no 😅 that must have been an accident, good catch. the same happened on react-spring and there it look a much darker turn

**Comment by CodyJasonBennett** [comment]
I'll try mirroring what we did over there to get the ball rolling with #64.
