### ISSUE TITLE
404 CSB iframe for Jotai + Redux page

### ISSUE THREAD

**Issue by alii** [pmndrs/website#68]
https://docs.pmnd.rs/jotai/integrations/redux has no CSB link:

![image](https://user-images.githubusercontent.com/25351731/116861410-f4132080-abfa-11eb-9e70-d3d3dffaad78.png)

**Comment by dai-shi** [comment]
Nice catch.

Looks like it's a simple mistake.
https://github.com/pmndrs/website/pull/46/files#diff-9f51de615cdfacd100dbe277ce2fe24d1f5c8b2a0cb571bb382f54a8d4b1b822

Would you like to file a PR to fix please?

**Comment by alii** [comment]
Sure, will do :rocket:

**Comment by SaraVieira** [comment]
Sorry about that, it was me when making it all embededs :/
