### ISSUE TITLE
There is no support for adding Fog to a Scene, or at least there is no documentation at all to say how to do that.

### ISSUE THREAD

**Issue by WilldelaVega777** [pmndrs/website#95]
The Scene object in Three js supports a fog property which allows to add a Fog object (as per documentation https://threejs.org/docs/index.html?q=Scene#api/en/scenes/Scene. This option is not available in React Three Fiber? at least that is what it seems.  There seems to be support for the feature using the CubeCamera, but what the documentation states is 

"Does it have limitations?
None. Everything that works in three.js will work here without exception."

Well, there seems to be one here :(

**Comment by drcmda** [comment]
```jsx
<Canvas onCreated={({ scene }) => scene.fog = new THREE.Fog("white", 10, 15)}>
```

or

```jsx
<Canvas>
  <fog attach="fog" args={["white", 10, 50]} />
```

here's an example https://codesandbox.io/s/volumetric-spotlight-tx1pq

generally, r3f is threejs. it uses a real THREE.Scene, THREE.Camera, etc, you can do the same things to these objects as in a plain three project.
