### ISSUE TITLE
docs routing give 404

### ISSUE THREAD

**Issue by Deep-Codes** [pmndrs/website#99]
Changing the Library Menu routes to incorrect route

![pmndrs](https://user-images.githubusercontent.com/61158210/121957513-1f536880-cd80-11eb-8005-37bb9803fea6.gif)

**Comment by Deep-Codes** [comment]
Should be Fixed in #98 if I am correct

**Comment by SaraVieira** [comment]
Yap, that was the issue and that PR is now merged :)
